---
name        : dChart 
tagline     : Fruity visualizations 
uri         : http://www.david-black.info
tagspace    : /tag/
email       : 
lang        : en
charset     : UTF-8
destination : _site 
server_port : 4000 
lsi         : false
pygments    : true
permalink   : /:year/:title/
markdown    : rdiscount
exclude     : [public, tmp, README.markdown, config.ru]
baseurl     : http://davidblackuk.github.io/canvas-dash/
