#!/bin/bash

productName="cDash"
jsFile="${productName}.js"
minFile="${productName}.min.js"

echo "Building cDash..."
tsc -out out/$jsFile ts/d/*.ts ts/common/*.ts ts/dials/needles/*.ts ts/dials/*.ts ts/marquee/*.ts ts/jQueryIntegration.ts
echo "Copy to docs..."
cp out/$jsFile ../canvas-dash-doc/js/$jsFile
echo "Done."

