#!/bin/bash

productName="cDash"
jsFile="${productName}.js"
mapFile="${jsFile}.map"
minFile="${productName}.min.js"


echo "Copy to docs..."
cp out/$jsFile ../canvas-dash-doc/js/$jsFile
cp out/$mapFile ../canvas-dash-doc/js/$mapFile
echo "Done."

